name: Get Origin IP

on:
  workflow_dispatch:  # 手動実行

jobs:
  find_origin_ip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Origin IP
        run: |
          TARGET_DOMAIN="example.com"  # ここに対象のドメインを入力
          ORIGIN_IP=$(dig +short "$TARGET_DOMAIN" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')
          
          if [ -n "$ORIGIN_IP" ]; then
            echo "Origin IP for $TARGET_DOMAIN: $ORIGIN_IP"
          else
            echo "No Origin IP found for $TARGET_DOMAIN"
            exit 1
          fi
