name: Display Origin IP

on: workflow_dispatch:
jobs: get-ip: runs-on: ubuntu-latest steps: - name: 指定したサイトの確認 run: echo "対象サイト：${{ github.event.inputs.site }}"


  - name: オリジンIPの取得（digコマンドを利用）
    run: |
      ip=$(dig +short ${{ github.event.inputs.site }})
      if [ -z "$ip" ]; then
        echo "IPの取得に失敗しました。"
        exit 1
      fi
      echo "オリジンIP: $ip"
